resolved issue where proper github id not being used
velocity-9/v9_deployment_manager pull request #26
Opened 2020-02-11 20:22 UTC by hjaensch7

2020-02-11 20:36 UTC, hjaensch7 commented
-[] - Add actual commit hash
-[] - Add queuing for race condition
-[] - Start all repos added when handling installation
-[] - Only deploy from default branch

2020-02-17 22:26 UTC, Others commented on pushHandler.go
> +		//wd, _ := os.Getwd()
Remove commented code

2020-02-17 22:30 UTC, Others requested changes

2020-02-17 22:30 UTC, Others commented on pushHandler.go
> +	//If first time installation get hash
Could be phrased more clearly

2020-02-17 22:30 UTC, Others commented on pushHandler.go
> +		//wd, _ := os.Getwd()
Remove commented code

2020-02-17 22:30 UTC, Others commented on cloneRepo.go
> +	hash = hash[:len(hash)-1]
If no input does this give a overwrite?

2020-02-17 22:30 UTC, Others commented on cloneRepo.go
> +		log.Error.Println(err)
return `err`?

2020-02-17 22:30 UTC, Others commented on cloneRepo.go
> +		log.Error.Println(err)
return `err`?

2020-02-17 22:41 UTC, Others approved these changes

2020-02-17 22:41 UTC, merged