Refactor how deployment works
velocity-9/v9_deployment_manager pull request #29
Opened 2020-02-25 05:40 UTC by Others

This boy is a chonker. I pulled out all the deployment logic into
a `deployment.ActionManager` object. It's a lot cleaner and now
handles a lot of cases we weren't handling before. (Like startup!)

It isn't perfect and the error handling is probably problematic,
so let's call this WIP. I also fixed a lot of little nits that
were bothering me during the refactor so the diff is kinda
unnecessarily large.

Really looking for feedback on this one!

2020-02-28 18:48 UTC, Others commented
@pcodes This is kinda a big change, can you also do a scan through for me?

2020-03-02 23:20 UTC, pcodes requested changes
There's a subtle bug in the ActionManager. Can you find it?

2020-03-02 23:20 UTC, pcodes commented on activator/git.go
> +	cmd := exec.Command("git", "checkout", hash)
Why have we switched away from just cloning the HEAD?

2020-03-02 23:20 UTC, pcodes commented on database/database.go
> +func (driver *Driver) FindComponentID(compID worker.ComponentID) (string, error) {
Why are these no longer pointers?

2020-03-02 23:20 UTC, pcodes commented on database/database.go
> +	}
What is this doing?

2020-03-02 23:20 UTC, pcodes commented on database/database.go
> +	compID, err := driver.FindComponentID(componentStatus.ID)
Why this change?

2020-03-02 23:20 UTC, pcodes commented on database/database.go
> +func (driver *Driver) FindActiveComponents() ([]worker.ComponentPath, error) {
Does the use of this function still work with the new method we have for "active" vs "pending" components? Or has that never mattered and only a front-end concept

2020-03-02 23:20 UTC, pcodes commented on deployment/actionManger.go
> +func (mgr *ActionManager) deactivateNonactive(w *worker.V9Worker, active []worker.ComponentPath) error {
I know nonactive is a word but it looks weird

2020-03-02 23:20 UTC, pcodes commented on deployment/actionManger.go
> +	// Otherwise pick a worker randomly and deploy there
Add TODO for load balancing?

2020-03-02 23:20 UTC, pcodes commented on handlers/apiHandler.go
> +	_, err = fmt.Fprintf(w, "10/4 Good Buddy")
lol

2020-03-02 23:20 UTC, pcodes commented on handlers/pushHandler.go
> +		log.Error.Println("Failed to find Github secret")
I think we should push the secret to github so we can always find it

2020-03-02 23:20 UTC, pcodes commented on handlers/pushHandler.go
> +		// NOTE: We don't know that the branch is correct, so we can't trust the head commit
I'm seeing this now after asking my initial question, would love to chat about this

2020-03-02 23:22 UTC, Others commented on activator/git.go
> +	cmd := exec.Command("git", "checkout", hash)
We uses hashes throughout for version consistency. If you pause and unpause, it makes sure to deploy the same commit (unless some event from Github has come along). I think the action manager might get confused if the deployment system just sends random hashes -- but I'm not 100% sure.

2020-03-02 23:23 UTC, Others commented on database/database.go
> +func (driver *Driver) FindComponentID(compID worker.ComponentID) (string, error) {
Pointers let you modify the original object. I thought that was scary and we don't use that functionality. So I removed the pointers

2020-03-02 23:23 UTC, Others commented on database/database.go
> +	}
It's just finding database component ids and storing them in `dbCIDs`

2020-03-02 23:23 UTC, Others commented on database/database.go
> +	compID, err := driver.FindComponentID(componentStatus.ID)
Goes with the other pointer removal change

2020-03-02 23:24 UTC, Others commented on database/database.go
> +func (driver *Driver) FindActiveComponents() ([]worker.ComponentPath, error) {
pending is a front end concept

2020-03-02 23:24 UTC, Others commented on deployment/actionManger.go
> +func (mgr *ActionManager) deactivateNonactive(w *worker.V9Worker, active []worker.ComponentPath) error {
Yeah it was a little painful to write this haha -- is there a better name you can think of?

2020-03-02 23:24 UTC, Others commented on deployment/actionManger.go
> +	// Otherwise pick a worker randomly and deploy there
@hjaensch7 is there an issue?

2020-03-02 23:25 UTC, pcodes commented on database/database.go
> +	}
What is a CID is more of my question

2020-03-02 23:37 UTC, Others commented
The subtle bug is the following:
- Timmy deploys a component from his repo `timmysGreatComponent`
- Timmy pushes a commit to his `dev` branch
- The deployment manager sees it should deploy (since there is a new push event)
- There are now two workers running identical versions of the component
- This situation remains until there is a push to `master`
- (so we could end up with timmy's component on every worker)

I think this means we need to be cleverer about push events -- make sure they come from the right branch or stop using the `HEAD` trick. We also could just clean up this situation in the auto scaling stack, but that seems inelegant.

@pcodes @hjaensch7

2020-03-09 19:08 UTC, hjaensch7 reviewed
This looks great. It's a big refactor so we should be sure that it's tested well. Just left a couple nits and marked some potential issues.

2020-03-09 19:08 UTC, hjaensch7 commented on database/pollingPopulator.go
>  		// TODO: Clear out old stats
Issue?

2020-03-09 19:08 UTC, hjaensch7 commented on deployment/actionManger.go
> +			// If we find someone running exactly this ID, we have ensured some worker is running this OD
nit: "OD" should be "ID"

2020-03-09 19:08 UTC, hjaensch7 commented on deployment/actionManger.go
> +	// TODO: Parallelize this step (it basically single threads the deployment manager at the moment)
issue?

2020-03-09 19:13 UTC, Others commented on database/database.go
> +	}
component id

2020-03-09 19:17 UTC, Others commented on database/pollingPopulator.go
>  		// TODO: Clear out old stats
#34

2020-03-09 19:17 UTC, Others commented on deployment/actionManger.go
> +	// TODO: Parallelize this step (it basically single threads the deployment manager at the moment)
#33

2020-03-09 19:19 UTC, Others commented
Pushed changes, also made issues for all the problems we need to resolve in future

2020-03-09 19:19 UTC, Others commented
@pcodes @hjaensch7 ready for re-review, should be ready to merge

2020-03-09 19:22 UTC, hjaensch7 approved these changes
Looks good, make a BUG issue for the infinite deploy bug

2020-04-08 15:42 UTC, pcodes approved these changes
So good I didn't even need to read it. Keep up the good documentation!

2020-04-08 15:48 UTC, merged